src/Entity/Cars.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Class Cars
 * @package App\Entity
 * @ORM\Entity
 */
class Cars{
        /**
         * @var integer
         * @ORM\Column(name="id", type="integer", nullable=false,
         *             options={"comment"="ID"})
         * @ORM\Id
         * @ORM\GeneratedValue(strategy="SEQUENCE")
         * @ORM\SequenceGenerator(sequenceName="seq_cars_id",
         *                        allocationSize=1, initialValue=1)
         */
        private $id;

        /**
         * @var string
         * @ORM\Column(name="car_name", type="string", nullable=false,
         *             options={"comment"="Car_name"})
         */
        private $car_name;

        /**
         * @var string
         * @ORM\Column(name="spz", type="string", nullable=false,
         *             options={"comment"="Spz"})
         */
        private $spz;

        /**
         * @var integer
         * @ORM\Column(name="number_of_seats", type="integer", nullable=false, options={"comment"="Number_of_seats"})
         */
        private $number_of_seats;

        /**
         * @var string
         * @ORM\Column(name="driver_first_name", type="string", nullable=false, options={"comment"="Driver_first_name"})
         */
        private $driver_first_name;

        /**
         * @var string
         * @ORM\Column(name="driver_last_name", type="string", nullable=false, options={"comment"="Driver_last_name"})
         */
        private $driver_last_name;

        /**
         * @return int
         */
        public function getId(): int
        {
            return $this->id;
        }

        /**
         * @param int $id
         */
        public function setId(int $id): void
        {
            $this->id = $id;
        }

        /**
         * @return string
         */
        public function getCarName(): string
        {
            return $this->car_name;
        }

        /**
         * @param string $car_name
         */
        public function setCarName(string $car_name): void
        {
            $this->car_name = $car_name;
        }

        /**
         * @return string
         */
        public function getSpz(): string
        {
            return $this->spz;
        }

        /**
         * @param string $spz
         */
        public function setSpz(string $spz): void
        {
            $this->spz = $spz;
        }

        /**
         * @return int
         */
        public function getNumberOfSeats(): int
        {
            return $this->number_of_seats;
        }

        /**
         * @param int $number_of_seats
         */
        public function setNumberOfSeats(int $number_of_seats): void
        {
            $this->number_of_seats = $number_of_seats;
        }

        /**
         * @return string
         */
        public function getDriverFirstName(): string
        {
            return $this->driver_first_name;
        }

        /**
         * @param string $driver_first_name
         */
        public function setDriverFirstName(string $driver_first_name): void
        {
            $this->driver_first_name = $driver_first_name;
        }

        /**
         * @return string
         */
        public function getDriverLastName(): string
        {
            return $this->driver_last_name;
        }

        /**
         * @param string $driver_last_name
         */
        public function setDriverLastName(string $driver_last_name): void
        {
            $this->driver_last_name = $driver_last_name;
        }


}

src/Entity/Users.php
<?php

namespace App\Entity;

use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Constraints\Date;
use Symfony\Component\Validator\Constraints\DateTimeValidator;
use Symfony\Component\Validator\Constraints\DateTime;

/**
     * Class Users
     * @package App\Entity
     * @ORM\Entity
     */
    class Users implements UserInterface, \Serializable
    {

        /**
         * @var integer
         * @ORM\Column(name="id",
         *             type="integer",
         *             nullable=false,
         *             options={"comment"="Id"})
         * @ORM\Id
         * @ORM\GeneratedValue(strategy="SEQUENCE")
         * @ORM\SequenceGenerator(sequenceName="seq_user_id",
         *                        allocationSize=1,
         *                        initialValue=1)
         */
        private $id;

        /**
         * @var string
         * @ORM\Column(name="first_name",
         *             type="string",
         *             nullable=true,
         *             options={"comment"="First name"})
         */
        private $firstName;

        /**
         * @var string
         * @ORM\Column(name="last_name",
         *             type="string",
         *             nullable=true,
         *             options={"comment"="Last name"})
         */
        private $lastName;

        /**
         * @var string
         * @ORM\Column(name="email", type="string", nullable=true, options={"comment"="Email"})
         */
        private $email;

        /**
         * @var string
         * @ORM\Column(name="username", type="string", nullable=true, options={"comment"="Username"})
         */
        private $username;

        /**
         * @var string
         * @ORM\Column(name="password", type="string", nullable=true, options={"comment"="Password"})
         */
        private $password;

        /**
         * @var string
         * @ORM\Column(name="salt", type="string", nullable=false, options={"default"="tmpSolution"})
         */
        private $salt;

        /**
         * @var string
         * @ORM\Column(name="address", type="string", nullable=true, options={"comment"="Address"})
         */
        private $address;

        /**
         * @var string
         * @ORM\Column(name="City", type="string", nullable=true, options={"comment"="City"})
         */
        private $city;

        /**
         * @var string
         * @ORM\Column(name="postal_code", type="string", nullable=true, options={"comment"="Postal code"})
         */
        private $postalCode;

        /**
         * @var string
         * @ORM\Column(name="school", type="string", nullable=true, options={"comment"="School"})
         */
        private $school;

        /**
         * @var DateTime
         * @ORM\Column(name="date_of_birth", type="datetime", nullable=false, options={"comment"="Date of birth"})
         */
        private DateTime $dateOfBirth;

        /**
         * @var integer
         * @ORM\Column(name="fines", type="integer", nullable=true, options={"comment"="Fines"})
         */
        private $fines;

        /**
         * @var integer
         * @ORM\Column(name="dress_number", type="integer", nullable=true, options={"comment"="Dress number"})
         */
        private $dressNumber;

        /**
         * @var string
         * @ORM\Column(name="auth_role", type="string", nullable=false, options={"comment"="Auth role"})
         */
        private $authRole;

        /**
         * @var string
         * @ORM\Column(name="phone_number_player", type="string", nullable=true, options={"comment"="Phone number player"})
         */
        private $phoneNumberPlayer;

        /**
         * @var string
         * @ORM\Column(name="phone_number_mother", type="string", nullable=true, options={"comment"="Phone number mother"})
         */
        private $phoneNumberMother;

        /**
         * @var string
         * @ORM\Column(name="phone_number_father", type="string", nullable=true, options={"comment"="Phone number father"})
         */
        private $phoneNumberFather;

        /**
         * @Assert\Length(min=7,
         *     minMessage="Heslo musí obsahovat minimálně 7 znaků.")
         * @Assert\Length(max=4096,
         *     maxMessage="Heslo může obsahovat maximálně 4096 znaků.")
         * @Assert\Regex(
         *     pattern="/\d/",
         *     match=true,
         *     message="Heslo musí obsahovat číslo."
         * )
         * @Assert\Regex(
         *     pattern="/[A-Z]/",
         *     match=true,
         *     message="Heslo musí obsahovat velké písmeno."
         * )
         * @Assert\Regex(
         *     pattern="/[a-z]/",
         *     match=true,
         *     message="Heslo musí obsahovat malé písmeno."
         * )
         */
        private $plainPassword;


        /**
         * @var \App\Entity\Category
         * @ORM\ManyToOne(targetEntity="App\Entity\Category")
         * @ORM\JoinColumn(name="category_id",
         *                 referencedColumnName="id",
         *                 nullable=true)
         */
        private $category;

        /**
         * @var integer
         * @ORM\Column(name="category_id",
         *             type="integer",
         *             nullable=true,
         *             options={"comment"="Category_id"})
         */
        protected $category_id;

        /**
         * @return int
         */
        public function getId()
        {
            return $this->id;
        }

        /**
         * @param int $id
         */
        public function setId(int $id): void
        {
            $this->id = $id;
        }

        /**
         * @return string
         */
        public function getFirstName()
        {
            return $this->firstName;
        }

        /**
         * @param string $firstName
         */
        public function setFirstName(string $firstName): void
        {
            $this->firstName = $firstName;
        }

        /**
         * @return string
         */
        public function getLastName()
        {
            return $this->lastName;
        }

        /**
         * @param string $lastName
         */
        public function setLastName(string $lastName): void
        {
            $this->lastName = $lastName;
        }

        /**
         * @return string
         */
        public function getEmail()
        {
            return $this->email;
        }

        /**
         * @param string $email
         */
        public function setEmail(string $email): void
        {
            $this->email = $email;
        }

        /**
         * @return string
         */
        public function getUsername(): string
        {
            return $this->username;
        }

        /**
         * @param string $username
         */
        public function setUsername(string $username): void
        {
            $this->username = $username;
        }

        /**
         * @return string
         */
        public function getPassword()
        {
            return $this->password;
        }

        /**
         * @param string $password
         */
        public function setPassword(string $password): void
        {
            $this->password = $password;
        }

        /**
         * @return string
         */
        public function getSalt()
        {
            return $this->salt;
        }

        /**
         * @param string $salt
         */
        public function setSalt(string $salt): void
        {
            $this->salt = $salt;
        }

        /**
         * @return string
         */
        public function getAddress()
        {
            return $this->address;
        }

        /**
         * @param string $address
         */
        public function setAddress(string $address): void
        {
            $this->address = $address;
        }

        /**
         * @return string
         */
        public function getCity()
        {
            return $this->city;
        }

        /**
         * @param string $city
         */
        public function setCity(string $city): void
        {
            $this->city = $city;
        }

        /**
         * @return string
         */
        public function getPostalCode()
        {
            return $this->postalCode;
        }

        /**
         * @param string $postalCode
         */
        public function setPostalCode(string $postalCode): void
        {
            $this->postalCode = $postalCode;
        }

        /**
         * @return string
         */
        public function getSchool()
        {
            return $this->school;
        }

        /**
         * @param string $school
         */
        public function setSchool(string $school): void
        {
            $this->school = $school;
        }

        public function getDateOfBirth()
        {
            return $this->dateOfBirth;
        }

        /**
         * @param DateTime $dateOfBirth
         */
        public function setDateOfBirth(DateTime $dateOfBirth)
        {
            $this->dateOfBirth = $dateOfBirth ;
        }

        /**
         * @return Category
         */
        public function getCategory(): ?Category
        {
            return $this->category;
        }

        /**
         * @param \App\Entity\Category|null $category
         */
        public function setCategory(Category $category = null): void
        {
            $this->category = $category;
        }

        /**
         * @return int
         */
        public function getCategoryId(): int
        {
            return $this->category_id;
        }

//        /**
//         * @param int $category_id
//         */
//        public function setCategoryId(int $category_id): void
//        {
//            $this->category_id = $category_id;
//        }

        /**

templates/addTeamMember.html.twig
{% extends 'base.html.twig' %}

{% block title %} IS BBK - Přidat hráče {% endblock %}

{% block body %}
    <div class="content">
        <div class="grid-container">
            <h3>Přidat nového hráče</h3>
            <div class="grid-x grid-padding-x">
                <div class="cell large-12">
                    {{ form_start(form) }}
                    {{ form_errors(form) }}
                </div>
                <div class="cell medium-6">
                    {{ form_row(form.username, {'label': 'Uživatelské jméno'}) }}

                    {{ form_row(form.firstName, {'label': 'Jméno'}) }}

                    {{ form_row(form.lastName, {'label': 'Příjmení'}) }}

                    {{ form_row(form.email, {'label': 'Email'}) }}

                    {{ form_row(form.address, {'label': 'Adresa'}) }}

                    {{ form_row(form.city, {'label': 'Město'}) }}

                    {{ form_row(form.postalCode, {'label': 'PSČ'}) }}

                    {{ form_row(form.school, {'label': 'Škola'}) }}
                </div>
                <div class="cell medium-6">
                    {{ form_row(form.plainPassword.first, {'label': 'Heslo'}) }}

                    {{ form_row(form.plainPassword.second, {'label': 'Heslo znovu'}) }}

                    {{ form_row(form.dateOfBirth, {'label': 'Datum narození'}) }}

                    {{ form_row(form.phoneNumberPlayer, {'label': 'Telefon hráč'}) }}

                    {{ form_row(form.phoneNumberMother, {'label': 'Telefon matka'} )}}

                    {{ form_row(form.phoneNumberFather, {'label': 'Telefon otec'}) }}

                    {{ form_row(form.category, {'label': 'Kategorie'}) }}
                </div>
            </div>
            <div class="text-center">
                {% if is_granted('ROLE_ADMIN') %}
                    <a href="{{ path('show-club', {'userId': app.user.getId()})}}" class="btn btn-warning" style="font-weight: bold">Zpět</a>
                    &nbsp;
                {% endif %}
                {% if is_granted('ROLE_COACH') or is_granted('ROLE_PLAYER') %}
                    <a href="{{ path('show-team', {'userId': app.user.getId()})}}" class="btn btn-warning" style="font-weight: bold">Zpět</a>
                    &nbsp;
                {% endif %}
                {{ form_widget(form.save, { 'label': 'Uložit změny', 'attr': { 'class': 'btn btn-success', 'style': 'font-weight: bold' }}) }}
            </div>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

templates/createStatistics.html.twig
{% extends 'base.html.twig' %}

{% block title %} IS BBK - Statistiky hráči{% endblock %}

{% block body %}

    <div class="container-fluid">
        <div class="row" style="width: 60%">
            <h2>Statistiky - hráči</h2>
            <table class="unstriped margin-top-1" id="table_statistics">
                <thead>
                    <tr class="row align-center">
                        <th class="column small-2 text-center">Kategorie</th>
                        <th class="column small-2 text-center">Jméno</th>
                        <th class="column small-2 text-center">Příjmení</th>
                        <th class="column small-2 text-center">Možnosti</th>
                    </tr>
                </thead>
                <tbody id="table_statistics">
                {% for user in users %}
                    <tr class="row align-center" style="margin-top: 2px">
                        {% if user.categoryId == 2 %}
                            <td class="columns small-2 text-center">U12</td>
                        {% elseif user.categoryId == 3 %}
                            <td class="columns small-2 text-center">U15</td>
                        {% elseif user.categoryId == 4 %}
                            <td class="columns small-2 text-center">U17</td>
                        {% elseif user.categoryId == 5 %}
                            <td class="columns small-2 text-center">U19/U20</td>
                        {% elseif user.categoryId == 1 %}
                            <td class="columns small-2 text-center">Admin</td>
                        {% endif %}
                        <td class="column small-2 text-center">{{ user.firstName }}</td>
                        <td class="column small-2 text-center">{{ user.lastName }}</td>
                        <td class="column small-2 text-center">
                            <a href="{{ path('create-statistics-user', {'userId': user.id}) }}" style="font-weight: bold">Vytvořit statistiku</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <div class="text-center">
                <a href="{{ path('show-team', {'userId': app.user.getId()}) }}" class="btn btn-warning" style="font-weight: bold">Zpět</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/createStatisticsUser.html.twig
{% extends 'base.html.twig' %}

{% block title %} IS BBK - Vytvořit statistiku{% endblock %}

{% block body %}
    <div class="content">
        <div class="grid-container">
            <h2>Vytvořit statistiku</h2>
            <div class="grid-x grid-padding-x">
                <div class="cell large-12">
                    {{ form_start(form) }}
                    {{ form_errors(form) }}
                </div>
                <div class="cell medium-6">
                    {{ form_row(form.successfulFt) }}

                    {{ form_row(form.unsuccessfulFt) }}

                    {{ form_row(form.twoPoints) }}
                </div>
                <div class="cell medium-6">
                    {{ form_row(form.threePoints) }}

                    {{ form_row(form.fouls) }}

                    {{ form_row(form.points) }}
                </div>
            </div>
            <div class="text-center">
                <a href="{{ path('show-statistics') }}" class="btn btn-warning">Zpět</a>
                &nbsp;
                {{ form_widget(form.save, { 'label': 'Uložit změny', 'attr': { 'class': 'btn btn-success' }}) }}
            </div>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

templates/editCar.html.twig
{% extends 'base.html.twig' %}

{% block title %} IS BBK - Editovat auto {% endblock %}

{% block body %}
    <div class="content">
        <div class="grid-container">
            <h3 class=>Editovat auto</h3>
            <div class="grid-x grid-padding-x">
                <div class="cell large-12">
                    {{ form_start(form) }}
                    {{ form_errors(form) }}
                </div>
                <div class="cell medium-6">
                    {{ form_row(form.carName) }}

                    {{ form_row(form.spz) }}

                    {{ form_row(form.numberOfSeats) }}

                    {{ form_row(form.driverFirstName) }}

                    {{ form_row(form.driverLastName) }}
                </div>
            </div>
                <a href="{{ path('show-cars')}}" class="btn btn-warning" style="font-weight: bold">Zpět</a>
                &nbsp;
                {{ form_widget(form.save, { 'label': 'Uložit změny', 'attr': { 'class': 'btn btn-success', 'style': 'font-weight: bold' }}) }}
            {{ form_end(form) }}
        </div>
    </div>

{% endblock %}

templates/editMatch.html.twig
{% extends 'base.html.twig' %}

{% block title %} IS BBK - Editovat zápas {{ match.homeTeam }} - {{ match.awayTeam }}{% endblock %}

{% block body %}
    <div class="content">
        <div class="grid-container">
            <h3 class="text-center">Editovat zápas {{ match.homeTeam }} - {{ match.awayTeam }}</h3>
            <div class="grid-x grid-padding-x">
                <div class="cell large-12">
                    {{ form_start(form) }}
                    {{ form_errors(form) }}
                </div>
                <div class="cell medium-6">
                    {{ form_row(form.homeTeam) }}

                    {{ form_row(form.awayTeam) }}

                    {{ form_row(form.matchTime) }}

                    {{ form_row(form.address) }}
                </div>
                <div class="cell medium-6">
                    {{ form_row(form.city) }}

                    {{ form_row(form.venue) }}

                    {{ form_row(form.postalCode) }}

                    {{ form_row(form.category) }}
                </div>
            </div>
            <div class="text-center">
                <a href="{{ path('show-matches')}}" class="btn btn-warning" style="font-weight: bold">Zpět</a>
                &nbsp;
                {{ form_widget(form.save, { 'label': 'Uložit změny', 'attr': { 'class': 'btn btn-success', 'style': 'font-weight: bold' }}) }}
            </div>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

templates/showAwayMatches.html.twig
{% extends 'base.html.twig' %}

{% block title %} IS BBK - Výjezdy{% endblock %}

{% block body %}
    <div class="grid-container">
        <div class="cell large-10">
            <h3>Výjezdy - venkovní zápasy</h3>
            <table class=" unstriped margin-top-1"  id="table_away_matches">
                <thead>
                    <tr class="row align-center">
                        <th class="columns small-2 text-center">Kategorie</th>
                        <th class="columns small-2 text-center">Domácí tým</th>
                        <th class="columns small-2 text-center">Hostující tým</th>
                        <th class="columns small-2 text-center">Čas</th>
                        <th class="columns small-2 text-center">Adresa</th>
                        <th class="columns small-2 text-center"></th>
                    </tr>
                </thead>
                <tbody id="table_away_matches">
                {% for match in matches %}
                    <tr class="row align-center">
                        {% if match.categoryId == 2 %}
                            <td class="columns small-2 text-center">U12</td>
                        {% elseif match.categoryId == 3 %}
                            <td class="columns small-2 text-center">U15</td>
                        {% elseif match.categoryId == 4 %}
                            <td class="columns small-2 text-center">U17</td>
                        {% elseif match.categoryId == 5 %}
                            <td class="columns small-2 text-center">U19/U20</td>
                        {% endif %}
                        <td class="columns small-2 text-center">{{ match.homeTeam }}</td>
                        <td class="columns small-2 text-center">{{ match.awayTeam }}</td>
                        <td class="columns small-2 text-center">{{ match.matchTime| date('H:i')}}</td>
                        <td class="columns small-2 text-center">{{ match.address }}, {{ match.city }}</td>
                        <td class="columns small-2 text-center" ><a href="{{ path('create-nomination', {'matchId': match.id}) }}" style="font-weight: bold">Nominace</a></td>

                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <div class="text-center">
                <a href="{{ path('show-matches') }}" class="btn btn-warning" style="font-weight: bold">Zpět</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/showCars.html.twig
{% extends 'base.html.twig' %}

{% block title %} IS BBK - Auta {% endblock %}

{% block body %}
    <div class="grid-container">
        <div class="cell large-10">
            <h3>Auta</h3>
            <a href="{{ path('create-cars')}}" class="btn btn-primary btn-sm" style="font-weight: bold">Přidat auto</a>
            <table class="unstriped margin-top-1"  id="table_cars">
                <thead>
                    <tr class="row align-center">
                        <th class="columns small-3 text-center">Vůz</th>
                        <th class="columns small-3 text-center">SPZ</th>
                        <th class="columns small-2 text-center">Počet míst</th>
                        <th class="columns small-2 text-center">řidič</th>
                        <th class="columns small-2 text-center">Akce</th>
                    </tr>
                </thead>
                <tbody id="table_cars">
                {% for car in cars %}
                    <tr class="row align-center">
                        <td class="columns small-3 text-center">{{ car.carName }}</td>
                        <td class="columns small-3 text-center">{{ car.spz }}</td>
                        <td class="columns small-2 text-center">{{ car.numberOfSeats}}</td>
                        <td class="columns small-2 text-center">{{ car.driverFirstName }} {{ car.driverLastName }}</td>
                        <td class="columns small-2 text-center"><a href="{{ path('edit-cars', {'carsId': car.id}) }}" style="font-weight: bold">Editovat</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/showTeam.html.twig
{% extends 'base.html.twig' %}

{% block title %} IS BBK - Tým{% endblock %}

{% block body %}
    <div class="container-fluid ">
                {% if app.user.getCategoryId == 2 %}
                    <h3>Tým U12</h3>
                {% elseif app.user.getCategoryId == 3 %}
                    <h3>Tým U15</h3>
                {% elseif app.user.getCategoryId == 4 %}
                    <h3>Tým U17</h3>
                {% elseif app.user.getCategoryId == 5 %}
                    <h3>Tým U19/U20</h3>
                {% elseif app.user.getCategoryId == 1 %}
                    <h3>Tým</h3>
                {% endif %}
        {% if is_granted('ROLE_ADMIN') or is_granted('ROLE_COACH') %}
            <a href="{{ path('add-user-team', {'userId': app.user.getId()}) }}" class="btn btn-primary btn-sm" style="font-weight: bold">Přidat hráče</a>
            <a href="{{ path('show-all-fines') }}" class="btn btn-danger btn-sm" style="font-weight: bold">Nezaplacené pokuty</a>
        {% endif %}
        <table class="unstriped margin-top-1" id="table_team">
            <thead>
                <tr class="row align-center">
                    <th class="column small-2 text-center">Kategorie</th>
                    <th class="column small-2 text-center">Jméno</th>
                    <th class="column small-2 text-center ">Příjmení</th>
                    <th class="column small-3 text-center">Datum narození</th>
                    <th class="column small-2 text-center" style="margin-left: 5px">Možnosti</th>
                </tr>
            </thead>
            <tbody id="table_team">
            {% for user in members %}
                <tr class="row align-center" style="margin-top: 2px">
                        {% if user.categoryId == 2 %}
                            <td class="column small-2 text-center">U12</td>
                        {% elseif user.categoryId == 3 %}
                            <td class="column small-2 text-center">U15</td>
                        {% elseif user.categoryId == 4 %}
                            <td class="column small-2 text-center">U17</td>
                        {% elseif user.categoryId == 5 %}
                            <td class="column small-2 text-center">U19/U20</td>
                        {% elseif user.categoryId == 1 %}
                            <td class="column small-2 text-center">Admin</td>
                        {% endif %}
                    <td class="column small-2 text-center">{{ user.firstName }}</td>
                    <td class="column small-2 text-center">{{ user.lastName }}</td>
                    <td class="column small-3 text-center">{{ user.dateOfBirth }}</td>
                    <td class="column small-2 text-center">
                        {% if is_granted('ROLE_ADMIN') or is_granted('ROLE_COACH') %}
                            <a href="{{ path('user-profile', {'userId' : user.id}) }}" style="font-weight: bold">Detail hráče</a>
                        {% endif %}
                        {% if is_granted('ROLE_PLAYER') %}
                            <a href="{{ path('user-detail-team', {'userId' : user.id}) }}" style="font-weight: bold">Detail hráče</a>
                        {% endif %}
                        {% if is_granted('ROLE_ADMIN') %}
                            <a href="{{ path('delete-user', {'userId' : user.id, 'usersId' : app.user.getId()}) }}" style="color: red; font-weight: bold">Odstranit</a>
                        {% endif %}
                        {% if is_granted('ROLE_COACH') %}
                            <a href="{{ path('delete-user-team', {'userId' : user.id, 'usersId' : app.user.getId()}) }}" style="color: red; font-weight: bold">Odstranit</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/userChangePassword.html.twig
{% extends 'base.html.twig' %}

{% block title %} IS BBK - Změnit heslo {% endblock %}

{% block body %}
    <div class="content">
        <div class="grid-container">
            <h3>Změnit heslo</h3>
            <div class="grid-x grid-padding-x">
                <div class="cell small-5">
                    {{ form_errors(form) }}
                    {{ form_start(form) }}
                    {{ form_row(form.plainPassword, { 'attr': { 'placeholder': 'Min. 8 znaků. Musí obsahovat velké písmeno, malé písmeno a číslici'  }}) }}

                    <a href="{{ path('user-detail')}}" class="btn btn-warning" style="font-weight: bold">Zpět</a>
                    &nbsp;
                    {{ form_widget(form.save, { 'label': 'Uložit změny', 'attr': { 'class': 'btn btn-success', 'style': 'font-weight: bold' }}) }}
                </div>
            </div>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}